Removed active profiles
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Malformed POM /root/.jenkins/workspace/Sample project/maven_sample_project/pom.xml: Unrecognised tag: 'activeProfiles' (position: START_TAG seen ...</profiles>\n  <activeProfiles>... @120:19)  @ /root/.jenkins/workspace/Sample project/maven_sample_project/pom.xml, line 120, column 19
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 53, column 15
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-javadoc-plugin is missing. @ line 66, column 15